# Generated by Django 5.2.3 on 2025-08-01 20:00

from django.db import migrations
from django.utils.text import slugify


def create_initial_data(apps, schema_editor):
    """Create initial data for Company and Category models."""
    Company = apps.get_model('jobs', 'Company')
    Category = apps.get_model('jobs', 'Category')
    
    # Create some sample companies
    companies = [
        {
            'name': 'TechCorp',
            'description': 'A leading technology company specializing in software development and IT services.',
            'website': 'https://techcorp.example.com',
            'industry': 'Information Technology',
            'company_size': '1001-5000',
            'headquarters': 'San Francisco, CA',
            'is_verified': True
        },
        {
            'name': 'DataSystems Inc',
            'description': 'Enterprise data solutions and business intelligence services.',
            'website': 'https://datasystems.example.com',
            'industry': 'Data & Analytics',
            'company_size': '501-1000',
            'headquarters': 'New York, NY',
            'is_verified': True
        },
        {
            'name': 'WebCraft Studios',
            'description': 'Creative web development and digital marketing agency.',
            'website': 'https://webcraft.example.com',
            'industry': 'Digital Marketing',
            'company_size': '11-50',
            'headquarters': 'Austin, TX',
            'is_verified': True
        }
    ]
    
    # Create sample categories
    categories = [
        {'name': 'Software Development', 'icon': 'fas fa-laptop-code'},
        {'name': 'Data Science', 'icon': 'fas fa-database'},
        {'name': 'Web Development', 'icon': 'fas fa-globe'},
        {'name': 'Mobile Development', 'icon': 'fas fa-mobile-alt'},
        {'name': 'DevOps', 'icon': 'fas fa-server'},
        {'name': 'UX/UI Design', 'icon': 'fas fa-paint-brush'},
        {'name': 'Product Management', 'icon': 'fas fa-tasks'},
        {'name': 'Marketing', 'icon': 'fas fa-bullhorn'},
        {'name': 'Sales', 'icon': 'fas fa-handshake'},
        {'name': 'Customer Support', 'icon': 'fas fa-headset'}
    ]
    
    # Create companies
    for company_data in companies:
        company_data['slug'] = slugify(company_data['name'])
        Company.objects.get_or_create(
            slug=company_data['slug'],
            defaults=company_data
        )
    
    # Create categories
    for category_data in categories:
        slug = slugify(category_data['name'])
        Category.objects.get_or_create(
            slug=slug,
            defaults={
                'name': category_data['name'],
                'icon': category_data['icon'],
                'description': f"Jobs in {category_data['name']}",
                'is_active': True
            }
        )


def reverse_migration(apps, schema_editor):
    """
    This migration can't be cleanly reversed, but we need to provide
    an empty function to satisfy the RunPython operation.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_migration),
    ]
